#!/bin/sh

set -eu

# creating gis user if it isn't already there
if ! getent passwd gis >/dev/null; then
        adduser --system --allow-bad-names --quiet \
            --home /var/tmp/gis --shell /bin/bash gis
        adduser gis netdev
fi

exit 0
